using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MineSharp.Data.Entities {
    public static class Entities {

        public static Dictionary<EntityType, EntityInfo> EntitiesByType = new Dictionary<EntityType,EntityInfo> ();

        private static EntityInfo RegisterInfo(EntityInfo entityInfo) {
            EntitiesByType.Add(entityInfo.Type, entityInfo);
            return entityInfo;
        }

        public static EntityInfo AREA_EFFECT_CLOUD = RegisterInfo(new EntityInfo() { Type = EntityType.area_effect_cloud, Category = EntityCategory.Other, Name = "area_effect_cloud", DisplayName = "Area Effect Cloud" });
        public static EntityInfo ARMOR_STAND = RegisterInfo(new EntityInfo() { Type = EntityType.armor_stand, Category = EntityCategory.Living, Name = "armor_stand", DisplayName = "Armor Stand" });
        public static EntityInfo ARROW = RegisterInfo(new EntityInfo() { Type = EntityType.arrow, Category = EntityCategory.Projectile, Name = "arrow", DisplayName = "Arrow" });
        public static EntityInfo AXOLOTL = RegisterInfo(new EntityInfo() { Type = EntityType.axolotl, Category = EntityCategory.Animal, Name = "axolotl", DisplayName = "Axolotl" });
        public static EntityInfo BAT = RegisterInfo(new EntityInfo() { Type = EntityType.bat, Category = EntityCategory.Ambient, Name = "bat", DisplayName = "Bat" });
        public static EntityInfo BEE = RegisterInfo(new EntityInfo() { Type = EntityType.bee, Category = EntityCategory.Animal, Name = "bee", DisplayName = "Bee" });
        public static EntityInfo BLAZE = RegisterInfo(new EntityInfo() { Type = EntityType.blaze, Category = EntityCategory.Hostile, Name = "blaze", DisplayName = "Blaze" });
        public static EntityInfo BOAT = RegisterInfo(new EntityInfo() { Type = EntityType.boat, Category = EntityCategory.Other, Name = "boat", DisplayName = "Boat" });
        public static EntityInfo CAT = RegisterInfo(new EntityInfo() { Type = EntityType.cat, Category = EntityCategory.Animal, Name = "cat", DisplayName = "Cat" });
        public static EntityInfo CAVE_SPIDER = RegisterInfo(new EntityInfo() { Type = EntityType.cave_spider, Category = EntityCategory.Hostile, Name = "cave_spider", DisplayName = "Cave Spider" });
        public static EntityInfo CHICKEN = RegisterInfo(new EntityInfo() { Type = EntityType.chicken, Category = EntityCategory.Animal, Name = "chicken", DisplayName = "Chicken" });
        public static EntityInfo COD = RegisterInfo(new EntityInfo() { Type = EntityType.cod, Category = EntityCategory.WaterCreature, Name = "cod", DisplayName = "Cod" });
        public static EntityInfo COW = RegisterInfo(new EntityInfo() { Type = EntityType.cow, Category = EntityCategory.Animal, Name = "cow", DisplayName = "Cow" });
        public static EntityInfo CREEPER = RegisterInfo(new EntityInfo() { Type = EntityType.creeper, Category = EntityCategory.Hostile, Name = "creeper", DisplayName = "Creeper" });
        public static EntityInfo DOLPHIN = RegisterInfo(new EntityInfo() { Type = EntityType.dolphin, Category = EntityCategory.WaterCreature, Name = "dolphin", DisplayName = "Dolphin" });
        public static EntityInfo DONKEY = RegisterInfo(new EntityInfo() { Type = EntityType.donkey, Category = EntityCategory.Animal, Name = "donkey", DisplayName = "Donkey" });
        public static EntityInfo DRAGON_FIREBALL = RegisterInfo(new EntityInfo() { Type = EntityType.dragon_fireball, Category = EntityCategory.Projectile, Name = "dragon_fireball", DisplayName = "Dragon Fireball" });
        public static EntityInfo DROWNED = RegisterInfo(new EntityInfo() { Type = EntityType.drowned, Category = EntityCategory.Hostile, Name = "drowned", DisplayName = "Drowned" });
        public static EntityInfo ELDER_GUARDIAN = RegisterInfo(new EntityInfo() { Type = EntityType.elder_guardian, Category = EntityCategory.Hostile, Name = "elder_guardian", DisplayName = "Elder Guardian" });
        public static EntityInfo END_CRYSTAL = RegisterInfo(new EntityInfo() { Type = EntityType.end_crystal, Category = EntityCategory.Other, Name = "end_crystal", DisplayName = "End Crystal" });
        public static EntityInfo ENDER_DRAGON = RegisterInfo(new EntityInfo() { Type = EntityType.ender_dragon, Category = EntityCategory.Mob, Name = "ender_dragon", DisplayName = "Ender Dragon" });
        public static EntityInfo ENDERMAN = RegisterInfo(new EntityInfo() { Type = EntityType.enderman, Category = EntityCategory.Hostile, Name = "enderman", DisplayName = "Enderman" });
        public static EntityInfo ENDERMITE = RegisterInfo(new EntityInfo() { Type = EntityType.endermite, Category = EntityCategory.Hostile, Name = "endermite", DisplayName = "Endermite" });
        public static EntityInfo EVOKER = RegisterInfo(new EntityInfo() { Type = EntityType.evoker, Category = EntityCategory.Hostile, Name = "evoker", DisplayName = "Evoker" });
        public static EntityInfo EVOKER_FANGS = RegisterInfo(new EntityInfo() { Type = EntityType.evoker_fangs, Category = EntityCategory.Other, Name = "evoker_fangs", DisplayName = "Evoker Fangs" });
        public static EntityInfo EXPERIENCE_ORB = RegisterInfo(new EntityInfo() { Type = EntityType.experience_orb, Category = EntityCategory.Other, Name = "experience_orb", DisplayName = "Experience Orb" });
        public static EntityInfo EYE_OF_ENDER = RegisterInfo(new EntityInfo() { Type = EntityType.eye_of_ender, Category = EntityCategory.Other, Name = "eye_of_ender", DisplayName = "Eye of Ender" });
        public static EntityInfo FALLING_BLOCK = RegisterInfo(new EntityInfo() { Type = EntityType.falling_block, Category = EntityCategory.Other, Name = "falling_block", DisplayName = "Falling Block" });
        public static EntityInfo FIREWORK_ROCKET = RegisterInfo(new EntityInfo() { Type = EntityType.firework_rocket, Category = EntityCategory.Projectile, Name = "firework_rocket", DisplayName = "Firework Rocket" });
        public static EntityInfo FOX = RegisterInfo(new EntityInfo() { Type = EntityType.fox, Category = EntityCategory.Animal, Name = "fox", DisplayName = "Fox" });
        public static EntityInfo GHAST = RegisterInfo(new EntityInfo() { Type = EntityType.ghast, Category = EntityCategory.Mob, Name = "ghast", DisplayName = "Ghast" });
        public static EntityInfo GIANT = RegisterInfo(new EntityInfo() { Type = EntityType.giant, Category = EntityCategory.Hostile, Name = "giant", DisplayName = "Giant" });
        public static EntityInfo GLOW_ITEM_FRAME = RegisterInfo(new EntityInfo() { Type = EntityType.glow_item_frame, Category = EntityCategory.Other, Name = "glow_item_frame", DisplayName = "Glow Item Frame" });
        public static EntityInfo GLOW_SQUID = RegisterInfo(new EntityInfo() { Type = EntityType.glow_squid, Category = EntityCategory.WaterCreature, Name = "glow_squid", DisplayName = "Glow Squid" });
        public static EntityInfo GOAT = RegisterInfo(new EntityInfo() { Type = EntityType.goat, Category = EntityCategory.Animal, Name = "goat", DisplayName = "Goat" });
        public static EntityInfo GUARDIAN = RegisterInfo(new EntityInfo() { Type = EntityType.guardian, Category = EntityCategory.Hostile, Name = "guardian", DisplayName = "Guardian" });
        public static EntityInfo HOGLIN = RegisterInfo(new EntityInfo() { Type = EntityType.hoglin, Category = EntityCategory.Animal, Name = "hoglin", DisplayName = "Hoglin" });
        public static EntityInfo HORSE = RegisterInfo(new EntityInfo() { Type = EntityType.horse, Category = EntityCategory.Animal, Name = "horse", DisplayName = "Horse" });
        public static EntityInfo HUSK = RegisterInfo(new EntityInfo() { Type = EntityType.husk, Category = EntityCategory.Hostile, Name = "husk", DisplayName = "Husk" });
        public static EntityInfo ILLUSIONER = RegisterInfo(new EntityInfo() { Type = EntityType.illusioner, Category = EntityCategory.Hostile, Name = "illusioner", DisplayName = "Illusioner" });
        public static EntityInfo IRON_GOLEM = RegisterInfo(new EntityInfo() { Type = EntityType.iron_golem, Category = EntityCategory.Mob, Name = "iron_golem", DisplayName = "Iron Golem" });
        public static EntityInfo ITEM = RegisterInfo(new EntityInfo() { Type = EntityType.item, Category = EntityCategory.Other, Name = "item", DisplayName = "Item" });
        public static EntityInfo ITEM_FRAME = RegisterInfo(new EntityInfo() { Type = EntityType.item_frame, Category = EntityCategory.Other, Name = "item_frame", DisplayName = "Item Frame" });
        public static EntityInfo FIREBALL = RegisterInfo(new EntityInfo() { Type = EntityType.fireball, Category = EntityCategory.Projectile, Name = "fireball", DisplayName = "Fireball" });
        public static EntityInfo LEASH_KNOT = RegisterInfo(new EntityInfo() { Type = EntityType.leash_knot, Category = EntityCategory.Other, Name = "leash_knot", DisplayName = "Leash Knot" });
        public static EntityInfo LIGHTNING_BOLT = RegisterInfo(new EntityInfo() { Type = EntityType.lightning_bolt, Category = EntityCategory.Other, Name = "lightning_bolt", DisplayName = "Lightning Bolt" });
        public static EntityInfo LLAMA = RegisterInfo(new EntityInfo() { Type = EntityType.llama, Category = EntityCategory.Animal, Name = "llama", DisplayName = "Llama" });
        public static EntityInfo LLAMA_SPIT = RegisterInfo(new EntityInfo() { Type = EntityType.llama_spit, Category = EntityCategory.Projectile, Name = "llama_spit", DisplayName = "Llama Spit" });
        public static EntityInfo MAGMA_CUBE = RegisterInfo(new EntityInfo() { Type = EntityType.magma_cube, Category = EntityCategory.Mob, Name = "magma_cube", DisplayName = "Magma Cube" });
        public static EntityInfo MARKER = RegisterInfo(new EntityInfo() { Type = EntityType.marker, Category = EntityCategory.Other, Name = "marker", DisplayName = "Marker" });
        public static EntityInfo MINECART = RegisterInfo(new EntityInfo() { Type = EntityType.minecart, Category = EntityCategory.Other, Name = "minecart", DisplayName = "Minecart" });
        public static EntityInfo CHEST_MINECART = RegisterInfo(new EntityInfo() { Type = EntityType.chest_minecart, Category = EntityCategory.Other, Name = "chest_minecart", DisplayName = "Minecart with Chest" });
        public static EntityInfo COMMAND_BLOCK_MINECART = RegisterInfo(new EntityInfo() { Type = EntityType.command_block_minecart, Category = EntityCategory.Other, Name = "command_block_minecart", DisplayName = "Minecart with Command Block" });
        public static EntityInfo FURNACE_MINECART = RegisterInfo(new EntityInfo() { Type = EntityType.furnace_minecart, Category = EntityCategory.Other, Name = "furnace_minecart", DisplayName = "Minecart with Furnace" });
        public static EntityInfo HOPPER_MINECART = RegisterInfo(new EntityInfo() { Type = EntityType.hopper_minecart, Category = EntityCategory.Other, Name = "hopper_minecart", DisplayName = "Minecart with Hopper" });
        public static EntityInfo SPAWNER_MINECART = RegisterInfo(new EntityInfo() { Type = EntityType.spawner_minecart, Category = EntityCategory.Other, Name = "spawner_minecart", DisplayName = "Minecart with Spawner" });
        public static EntityInfo TNT_MINECART = RegisterInfo(new EntityInfo() { Type = EntityType.tnt_minecart, Category = EntityCategory.Other, Name = "tnt_minecart", DisplayName = "Minecart with TNT" });
        public static EntityInfo MULE = RegisterInfo(new EntityInfo() { Type = EntityType.mule, Category = EntityCategory.Animal, Name = "mule", DisplayName = "Mule" });
        public static EntityInfo MOOSHROOM = RegisterInfo(new EntityInfo() { Type = EntityType.mooshroom, Category = EntityCategory.Animal, Name = "mooshroom", DisplayName = "Mooshroom" });
        public static EntityInfo OCELOT = RegisterInfo(new EntityInfo() { Type = EntityType.ocelot, Category = EntityCategory.Animal, Name = "ocelot", DisplayName = "Ocelot" });
        public static EntityInfo PAINTING = RegisterInfo(new EntityInfo() { Type = EntityType.painting, Category = EntityCategory.Other, Name = "painting", DisplayName = "Painting" });
        public static EntityInfo PANDA = RegisterInfo(new EntityInfo() { Type = EntityType.panda, Category = EntityCategory.Animal, Name = "panda", DisplayName = "Panda" });
        public static EntityInfo PARROT = RegisterInfo(new EntityInfo() { Type = EntityType.parrot, Category = EntityCategory.Animal, Name = "parrot", DisplayName = "Parrot" });
        public static EntityInfo PHANTOM = RegisterInfo(new EntityInfo() { Type = EntityType.phantom, Category = EntityCategory.Mob, Name = "phantom", DisplayName = "Phantom" });
        public static EntityInfo PIG = RegisterInfo(new EntityInfo() { Type = EntityType.pig, Category = EntityCategory.Animal, Name = "pig", DisplayName = "Pig" });
        public static EntityInfo PIGLIN = RegisterInfo(new EntityInfo() { Type = EntityType.piglin, Category = EntityCategory.Hostile, Name = "piglin", DisplayName = "Piglin" });
        public static EntityInfo PIGLIN_BRUTE = RegisterInfo(new EntityInfo() { Type = EntityType.piglin_brute, Category = EntityCategory.Hostile, Name = "piglin_brute", DisplayName = "Piglin Brute" });
        public static EntityInfo PILLAGER = RegisterInfo(new EntityInfo() { Type = EntityType.pillager, Category = EntityCategory.Hostile, Name = "pillager", DisplayName = "Pillager" });
        public static EntityInfo POLAR_BEAR = RegisterInfo(new EntityInfo() { Type = EntityType.polar_bear, Category = EntityCategory.Animal, Name = "polar_bear", DisplayName = "Polar Bear" });
        public static EntityInfo TNT = RegisterInfo(new EntityInfo() { Type = EntityType.tnt, Category = EntityCategory.Other, Name = "tnt", DisplayName = "Primed TNT" });
        public static EntityInfo PUFFERFISH = RegisterInfo(new EntityInfo() { Type = EntityType.pufferfish, Category = EntityCategory.WaterCreature, Name = "pufferfish", DisplayName = "Pufferfish" });
        public static EntityInfo RABBIT = RegisterInfo(new EntityInfo() { Type = EntityType.rabbit, Category = EntityCategory.Animal, Name = "rabbit", DisplayName = "Rabbit" });
        public static EntityInfo RAVAGER = RegisterInfo(new EntityInfo() { Type = EntityType.ravager, Category = EntityCategory.Hostile, Name = "ravager", DisplayName = "Ravager" });
        public static EntityInfo SALMON = RegisterInfo(new EntityInfo() { Type = EntityType.salmon, Category = EntityCategory.WaterCreature, Name = "salmon", DisplayName = "Salmon" });
        public static EntityInfo SHEEP = RegisterInfo(new EntityInfo() { Type = EntityType.sheep, Category = EntityCategory.Animal, Name = "sheep", DisplayName = "Sheep" });
        public static EntityInfo SHULKER = RegisterInfo(new EntityInfo() { Type = EntityType.shulker, Category = EntityCategory.Mob, Name = "shulker", DisplayName = "Shulker" });
        public static EntityInfo SHULKER_BULLET = RegisterInfo(new EntityInfo() { Type = EntityType.shulker_bullet, Category = EntityCategory.Projectile, Name = "shulker_bullet", DisplayName = "Shulker Bullet" });
        public static EntityInfo SILVERFISH = RegisterInfo(new EntityInfo() { Type = EntityType.silverfish, Category = EntityCategory.Hostile, Name = "silverfish", DisplayName = "Silverfish" });
        public static EntityInfo SKELETON = RegisterInfo(new EntityInfo() { Type = EntityType.skeleton, Category = EntityCategory.Hostile, Name = "skeleton", DisplayName = "Skeleton" });
        public static EntityInfo SKELETON_HORSE = RegisterInfo(new EntityInfo() { Type = EntityType.skeleton_horse, Category = EntityCategory.Animal, Name = "skeleton_horse", DisplayName = "Skeleton Horse" });
        public static EntityInfo SLIME = RegisterInfo(new EntityInfo() { Type = EntityType.slime, Category = EntityCategory.Mob, Name = "slime", DisplayName = "Slime" });
        public static EntityInfo SMALL_FIREBALL = RegisterInfo(new EntityInfo() { Type = EntityType.small_fireball, Category = EntityCategory.Projectile, Name = "small_fireball", DisplayName = "Small Fireball" });
        public static EntityInfo SNOW_GOLEM = RegisterInfo(new EntityInfo() { Type = EntityType.snow_golem, Category = EntityCategory.Mob, Name = "snow_golem", DisplayName = "Snow Golem" });
        public static EntityInfo SNOWBALL = RegisterInfo(new EntityInfo() { Type = EntityType.snowball, Category = EntityCategory.Projectile, Name = "snowball", DisplayName = "Snowball" });
        public static EntityInfo SPECTRAL_ARROW = RegisterInfo(new EntityInfo() { Type = EntityType.spectral_arrow, Category = EntityCategory.Projectile, Name = "spectral_arrow", DisplayName = "Spectral Arrow" });
        public static EntityInfo SPIDER = RegisterInfo(new EntityInfo() { Type = EntityType.spider, Category = EntityCategory.Hostile, Name = "spider", DisplayName = "Spider" });
        public static EntityInfo SQUID = RegisterInfo(new EntityInfo() { Type = EntityType.squid, Category = EntityCategory.WaterCreature, Name = "squid", DisplayName = "Squid" });
        public static EntityInfo STRAY = RegisterInfo(new EntityInfo() { Type = EntityType.stray, Category = EntityCategory.Hostile, Name = "stray", DisplayName = "Stray" });
        public static EntityInfo STRIDER = RegisterInfo(new EntityInfo() { Type = EntityType.strider, Category = EntityCategory.Animal, Name = "strider", DisplayName = "Strider" });
        public static EntityInfo EGG = RegisterInfo(new EntityInfo() { Type = EntityType.egg, Category = EntityCategory.Projectile, Name = "egg", DisplayName = "Thrown Egg" });
        public static EntityInfo ENDER_PEARL = RegisterInfo(new EntityInfo() { Type = EntityType.ender_pearl, Category = EntityCategory.Projectile, Name = "ender_pearl", DisplayName = "Thrown Ender Pearl" });
        public static EntityInfo EXPERIENCE_BOTTLE = RegisterInfo(new EntityInfo() { Type = EntityType.experience_bottle, Category = EntityCategory.Projectile, Name = "experience_bottle", DisplayName = "Thrown Bottle o' Enchanting" });
        public static EntityInfo POTION = RegisterInfo(new EntityInfo() { Type = EntityType.potion, Category = EntityCategory.Projectile, Name = "potion", DisplayName = "Potion" });
        public static EntityInfo TRIDENT = RegisterInfo(new EntityInfo() { Type = EntityType.trident, Category = EntityCategory.Projectile, Name = "trident", DisplayName = "Trident" });
        public static EntityInfo TRADER_LLAMA = RegisterInfo(new EntityInfo() { Type = EntityType.trader_llama, Category = EntityCategory.Animal, Name = "trader_llama", DisplayName = "Trader Llama" });
        public static EntityInfo TROPICAL_FISH = RegisterInfo(new EntityInfo() { Type = EntityType.tropical_fish, Category = EntityCategory.WaterCreature, Name = "tropical_fish", DisplayName = "Tropical Fish" });
        public static EntityInfo TURTLE = RegisterInfo(new EntityInfo() { Type = EntityType.turtle, Category = EntityCategory.Animal, Name = "turtle", DisplayName = "Turtle" });
        public static EntityInfo VEX = RegisterInfo(new EntityInfo() { Type = EntityType.vex, Category = EntityCategory.Hostile, Name = "vex", DisplayName = "Vex" });
        public static EntityInfo VILLAGER = RegisterInfo(new EntityInfo() { Type = EntityType.villager, Category = EntityCategory.Passive, Name = "villager", DisplayName = "Villager" });
        public static EntityInfo VINDICATOR = RegisterInfo(new EntityInfo() { Type = EntityType.vindicator, Category = EntityCategory.Hostile, Name = "vindicator", DisplayName = "Vindicator" });
        public static EntityInfo WANDERING_TRADER = RegisterInfo(new EntityInfo() { Type = EntityType.wandering_trader, Category = EntityCategory.Passive, Name = "wandering_trader", DisplayName = "Wandering Trader" });
        public static EntityInfo WITCH = RegisterInfo(new EntityInfo() { Type = EntityType.witch, Category = EntityCategory.Hostile, Name = "witch", DisplayName = "Witch" });
        public static EntityInfo WITHER = RegisterInfo(new EntityInfo() { Type = EntityType.wither, Category = EntityCategory.Hostile, Name = "wither", DisplayName = "Wither" });
        public static EntityInfo WITHER_SKELETON = RegisterInfo(new EntityInfo() { Type = EntityType.wither_skeleton, Category = EntityCategory.Hostile, Name = "wither_skeleton", DisplayName = "Wither Skeleton" });
        public static EntityInfo WITHER_SKULL = RegisterInfo(new EntityInfo() { Type = EntityType.wither_skull, Category = EntityCategory.Projectile, Name = "wither_skull", DisplayName = "Wither Skull" });
        public static EntityInfo WOLF = RegisterInfo(new EntityInfo() { Type = EntityType.wolf, Category = EntityCategory.Animal, Name = "wolf", DisplayName = "Wolf" });
        public static EntityInfo ZOGLIN = RegisterInfo(new EntityInfo() { Type = EntityType.zoglin, Category = EntityCategory.Hostile, Name = "zoglin", DisplayName = "Zoglin" });
        public static EntityInfo ZOMBIE = RegisterInfo(new EntityInfo() { Type = EntityType.zombie, Category = EntityCategory.Hostile, Name = "zombie", DisplayName = "Zombie" });
        public static EntityInfo ZOMBIE_HORSE = RegisterInfo(new EntityInfo() { Type = EntityType.zombie_horse, Category = EntityCategory.Animal, Name = "zombie_horse", DisplayName = "Zombie Horse" });
        public static EntityInfo ZOMBIE_VILLAGER = RegisterInfo(new EntityInfo() { Type = EntityType.zombie_villager, Category = EntityCategory.Hostile, Name = "zombie_villager", DisplayName = "Zombie Villager" });
        public static EntityInfo ZOMBIFIED_PIGLIN = RegisterInfo(new EntityInfo() { Type = EntityType.zombified_piglin, Category = EntityCategory.Hostile, Name = "zombified_piglin", DisplayName = "Zombified Piglin" });
        public static EntityInfo PLAYER = RegisterInfo(new EntityInfo() { Type = EntityType.player, Category = EntityCategory.Player, Name = "player", DisplayName = "Player" });
        public static EntityInfo FISHING_BOBBER = RegisterInfo(new EntityInfo() { Type = EntityType.fishing_bobber, Category = EntityCategory.Projectile, Name = "fishing_bobber", DisplayName = "Fishing Bobber" });
    }
}
