///////////////////////////////////////////////////////////////////////////////////////////
//    This File is generated by MineSharp.SourceGenerator and should not be modified.    //
///////////////////////////////////////////////////////////////////////////////////////////
namespace MineSharp.Core.Common.Blocks;

public enum Material
{
    Default = 0,
    Pickaxe = 1,
    Shovel = 2,
    Axe = 3,
    Plant = 4,
    Leaves = 5,
    Hoe = 6,
    Cobweb = 7,
    Wool = 8,
    Gourd = 9,
    VineOrGlowLichen = 10,
}
