///////////////////////////////////////////////////////////////////////////////////////////
//    This File is generated by MineSharp.SourceGenerator and should not be modified.    //
///////////////////////////////////////////////////////////////////////////////////////////

#pragma warning disable CS1591

namespace MineSharp.Core.Common.Biomes;

public enum BiomeCategory
{
    None = 0,
    Plains = 1,
    Ice = 2,
    Desert = 3,
    Swamp = 4,
    Forest = 5,
    Taiga = 6,
    Savanna = 7,
    ExtremeHills = 8,
    Jungle = 9,
    Mesa = 10,
    Mountain = 11,
    River = 12,
    Beach = 13,
    Ocean = 14,
    Mushroom = 15,
    Underground = 16,
    Nether = 17,
    TheEnd = 18,
}

#pragma warning restore CS1591
