///////////////////////////////////////////////////////////////////////////////////////////
//    This File is generated by MineSharp.SourceGenerator and should not be modified.    //
///////////////////////////////////////////////////////////////////////////////////////////
namespace MineSharp.Core.Common.Biomes;

public enum BiomeCategory
{
    Mesa = 0,
    Jungle = 1,
    Nether = 2,
    Beach = 3,
    Forest = 4,
    Ocean = 5,
    Underground = 6,
    Desert = 7,
    TheEnd = 8,
    Ice = 9,
    Mountain = 10,
    Mushroom = 11,
    Taiga = 12,
    Plains = 13,
    River = 14,
    Savanna = 15,
    Swamp = 16,
    None = 17,
    ExtremeHills = 18,
}
