///////////////////////////////////////////////////////////////////////////////////////////
//    This File is generated by MineSharp.SourceGenerator and should not be modified.    //
///////////////////////////////////////////////////////////////////////////////////////////

#pragma warning disable CS1591

namespace MineSharp.Core.Common.Enchantments;

public enum EnchantmentType
{
    Protection = 0,
    FireProtection = 1,
    FeatherFalling = 2,
    BlastProtection = 3,
    ProjectileProtection = 4,
    Respiration = 5,
    AquaAffinity = 6,
    Thorns = 7,
    DepthStrider = 8,
    FrostWalker = 9,
    BindingCurse = 10,
    SoulSpeed = 11,
    Sharpness = 12,
    Smite = 13,
    BaneOfArthropods = 14,
    Knockback = 15,
    FireAspect = 16,
    Looting = 17,
    Sweeping = 18,
    Efficiency = 19,
    SilkTouch = 20,
    Unbreaking = 21,
    Fortune = 22,
    Power = 23,
    Punch = 24,
    Flame = 25,
    Infinity = 26,
    LuckOfTheSea = 27,
    Lure = 28,
    Loyalty = 29,
    Impaling = 30,
    Riptide = 31,
    Channeling = 32,
    Multishot = 33,
    QuickCharge = 34,
    Piercing = 35,
    Mending = 36,
    VanishingCurse = 37,
    SwiftSneak = 38,
    SweepingEdge = 39,
    Density = 40,
    Breach = 41,
    WindBurst = 42,
}

#pragma warning restore CS1591
