///////////////////////////////////////////////////////////////////////////////////////////
//    This File is generated by MineSharp.SourceGenerator and should not be modified.    //
///////////////////////////////////////////////////////////////////////////////////////////

#pragma warning disable CS1591

namespace MineSharp.Core.Common.Enchantments;

public enum EnchantmentCategory
{
    Armor = 0,
    ArmorFeet = 1,
    ArmorHead = 2,
    ArmorChest = 3,
    Wearable = 4,
    Weapon = 5,
    Digger = 6,
    Breakable = 7,
    Bow = 8,
    FishingRod = 9,
    Trident = 10,
    Crossbow = 11,
    Vanishable = 12,
    ArmorLegs = 13,
}

#pragma warning restore CS1591
