///////////////////////////////////////////////////////////////////////////////////////////
//    This File is generated by MineSharp.SourceGenerator and should not be modified.    //
///////////////////////////////////////////////////////////////////////////////////////////

#pragma warning disable CS1591

namespace MineSharp.Core.Common.Enchantments;

public enum EnchantmentType
{
    Protection = 0,
    FireProtection = 1,
    FeatherFalling = 2,
    BlastProtection = 3,
    ProjectileProtection = 4,
    Respiration = 5,
    AquaAffinity = 6,
    Thorns = 7,
    DepthStrider = 8,
    FrostWalker = 9,
    BindingCurse = 10,
    SoulSpeed = 11,
    SwiftSneak = 12,
    Sharpness = 13,
    Smite = 14,
    BaneOfArthropods = 15,
    Knockback = 16,
    FireAspect = 17,
    Looting = 18,
    Sweeping = 19,
    Efficiency = 20,
    SilkTouch = 21,
    Unbreaking = 22,
    Fortune = 23,
    Power = 24,
    Punch = 25,
    Flame = 26,
    Infinity = 27,
    LuckOfTheSea = 28,
    Lure = 29,
    Loyalty = 30,
    Impaling = 31,
    Riptide = 32,
    Channeling = 33,
    Multishot = 34,
    QuickCharge = 35,
    Piercing = 36,
    Mending = 37,
    VanishingCurse = 38,
}

#pragma warning restore CS1591
