///////////////////////////////////////////////////////////////////////////////////////////
//    This File is generated by MineSharp.SourceGenerator and should not be modified.    //
///////////////////////////////////////////////////////////////////////////////////////////

#pragma warning disable CS1591

namespace MineSharp.Core.Common.Enchantments;

public enum EnchantmentCategory
{
    Armor = 0,
    ArmorFeet = 1,
    ArmorHead = 2,
    ArmorChest = 3,
    Wearable = 4,
    ArmorLegs = 5,
    Weapon = 6,
    Digger = 7,
    Breakable = 8,
    Bow = 9,
    FishingRod = 10,
    Trident = 11,
    Crossbow = 12,
    Vanishable = 13,
}

#pragma warning restore CS1591
