///////////////////////////////////////////////////////////////////////////////////////////
//    This File is generated by MineSharp.SourceGenerator and should not be modified.    //
///////////////////////////////////////////////////////////////////////////////////////////

#pragma warning disable CS1591

namespace MineSharp.Core.Common.Entities;

public enum EntityCategory
{
    Unknown = 0,
    PassiveMobs = 1,
    Immobile = 2,
    Projectiles = 3,
    HostileMobs = 4,
    Vehicles = 5,
}

#pragma warning restore CS1591
