///////////////////////////////////////////////////////////////////////////////////////////
//    This File is generated by MineSharp.SourceGenerator and should not be modified.    //
///////////////////////////////////////////////////////////////////////////////////////////
namespace MineSharp.Core.Common.Entities;

public enum EntityCategory
{
    PassiveMobs = 0,
    Unknown = 1,
    Immobile = 2,
    Projectiles = 3,
    HostileMobs = 4,
    Vehicles = 5,
}
