///////////////////////////////////////////////////////////////////////////////////////////
//    This File is generated by MineSharp.SourceGenerator and should not be modified.    //
///////////////////////////////////////////////////////////////////////////////////////////
namespace MineSharp.Data;

internal static class VersionMap
{
    public static Dictionary<string, string> Biomes { get; } = new()
    {
        { "1.18", "MineSharp.Data.Biomes.Versions.Biomes_1_18" },
        { "1.18.1", "MineSharp.Data.Biomes.Versions.Biomes_1_18" },
        { "1.18.2", "MineSharp.Data.Biomes.Versions.Biomes_1_18" },
        { "1.19", "MineSharp.Data.Biomes.Versions.Biomes_1_19" },
        { "1.19.2", "MineSharp.Data.Biomes.Versions.Biomes_1_19_2" },
        { "1.19.3", "MineSharp.Data.Biomes.Versions.Biomes_1_19_3" },
        { "1.19.4", "MineSharp.Data.Biomes.Versions.Biomes_1_19_4" },
        { "1.20", "MineSharp.Data.Biomes.Versions.Biomes_1_20" },
        { "1.20.1", "MineSharp.Data.Biomes.Versions.Biomes_1_20" },
        { "1.20.2", "MineSharp.Data.Biomes.Versions.Biomes_1_20_2" },
    };
    public static Dictionary<string, string> Blocks { get; } = new()
    {
        { "1.18", "MineSharp.Data.Blocks.Versions.Blocks_1_18" },
        { "1.18.1", "MineSharp.Data.Blocks.Versions.Blocks_1_18" },
        { "1.18.2", "MineSharp.Data.Blocks.Versions.Blocks_1_18" },
        { "1.19", "MineSharp.Data.Blocks.Versions.Blocks_1_19" },
        { "1.19.2", "MineSharp.Data.Blocks.Versions.Blocks_1_19_2" },
        { "1.19.3", "MineSharp.Data.Blocks.Versions.Blocks_1_19_3" },
        { "1.19.4", "MineSharp.Data.Blocks.Versions.Blocks_1_19_4" },
        { "1.20", "MineSharp.Data.Blocks.Versions.Blocks_1_20" },
        { "1.20.1", "MineSharp.Data.Blocks.Versions.Blocks_1_20" },
        { "1.20.2", "MineSharp.Data.Blocks.Versions.Blocks_1_20_2" },
    };
    public static Dictionary<string, string> BlockCollisionShapes { get; } = new()
    {
        { "1.18", "MineSharp.Data.BlockCollisionShapes.Versions.BlockCollisionShapes_1_17" },
        { "1.18.1", "MineSharp.Data.BlockCollisionShapes.Versions.BlockCollisionShapes_1_17" },
        { "1.18.2", "MineSharp.Data.BlockCollisionShapes.Versions.BlockCollisionShapes_1_17" },
        { "1.19", "MineSharp.Data.BlockCollisionShapes.Versions.BlockCollisionShapes_1_19" },
        { "1.19.2", "MineSharp.Data.BlockCollisionShapes.Versions.BlockCollisionShapes_1_19_2" },
        { "1.19.3", "MineSharp.Data.BlockCollisionShapes.Versions.BlockCollisionShapes_1_19_3" },
        { "1.19.4", "MineSharp.Data.BlockCollisionShapes.Versions.BlockCollisionShapes_1_19_4" },
        { "1.20", "MineSharp.Data.BlockCollisionShapes.Versions.BlockCollisionShapes_1_20" },
        { "1.20.1", "MineSharp.Data.BlockCollisionShapes.Versions.BlockCollisionShapes_1_20" },
        { "1.20.2", "MineSharp.Data.BlockCollisionShapes.Versions.BlockCollisionShapes_1_20_2" },
    };
    public static Dictionary<string, string> Effects { get; } = new()
    {
        { "1.18", "MineSharp.Data.Effects.Versions.Effects_1_17" },
        { "1.18.1", "MineSharp.Data.Effects.Versions.Effects_1_17" },
        { "1.18.2", "MineSharp.Data.Effects.Versions.Effects_1_17" },
        { "1.19", "MineSharp.Data.Effects.Versions.Effects_1_19" },
        { "1.19.2", "MineSharp.Data.Effects.Versions.Effects_1_19_2" },
        { "1.19.3", "MineSharp.Data.Effects.Versions.Effects_1_19_3" },
        { "1.19.4", "MineSharp.Data.Effects.Versions.Effects_1_19_4" },
        { "1.20", "MineSharp.Data.Effects.Versions.Effects_1_20" },
        { "1.20.1", "MineSharp.Data.Effects.Versions.Effects_1_20" },
        { "1.20.2", "MineSharp.Data.Effects.Versions.Effects_1_20_2" },
    };
    public static Dictionary<string, string> Enchantments { get; } = new()
    {
        { "1.18", "MineSharp.Data.Enchantments.Versions.Enchantments_1_17" },
        { "1.18.1", "MineSharp.Data.Enchantments.Versions.Enchantments_1_17" },
        { "1.18.2", "MineSharp.Data.Enchantments.Versions.Enchantments_1_17" },
        { "1.19", "MineSharp.Data.Enchantments.Versions.Enchantments_1_19" },
        { "1.19.2", "MineSharp.Data.Enchantments.Versions.Enchantments_1_19_2" },
        { "1.19.3", "MineSharp.Data.Enchantments.Versions.Enchantments_1_19_3" },
        { "1.19.4", "MineSharp.Data.Enchantments.Versions.Enchantments_1_19_4" },
        { "1.20", "MineSharp.Data.Enchantments.Versions.Enchantments_1_20" },
        { "1.20.1", "MineSharp.Data.Enchantments.Versions.Enchantments_1_20" },
        { "1.20.2", "MineSharp.Data.Enchantments.Versions.Enchantments_1_20_2" },
    };
    public static Dictionary<string, string> Entities { get; } = new()
    {
        { "1.18", "MineSharp.Data.Entities.Versions.Entities_1_18" },
        { "1.18.1", "MineSharp.Data.Entities.Versions.Entities_1_18" },
        { "1.18.2", "MineSharp.Data.Entities.Versions.Entities_1_18" },
        { "1.19", "MineSharp.Data.Entities.Versions.Entities_1_19" },
        { "1.19.2", "MineSharp.Data.Entities.Versions.Entities_1_19_2" },
        { "1.19.3", "MineSharp.Data.Entities.Versions.Entities_1_19_3" },
        { "1.19.4", "MineSharp.Data.Entities.Versions.Entities_1_19_4" },
        { "1.20", "MineSharp.Data.Entities.Versions.Entities_1_20" },
        { "1.20.1", "MineSharp.Data.Entities.Versions.Entities_1_20" },
        { "1.20.2", "MineSharp.Data.Entities.Versions.Entities_1_20_2" },
    };
    public static Dictionary<string, string> Items { get; } = new()
    {
        { "1.18", "MineSharp.Data.Items.Versions.Items_1_18" },
        { "1.18.1", "MineSharp.Data.Items.Versions.Items_1_18" },
        { "1.18.2", "MineSharp.Data.Items.Versions.Items_1_18" },
        { "1.19", "MineSharp.Data.Items.Versions.Items_1_19" },
        { "1.19.2", "MineSharp.Data.Items.Versions.Items_1_19_2" },
        { "1.19.3", "MineSharp.Data.Items.Versions.Items_1_19_3" },
        { "1.19.4", "MineSharp.Data.Items.Versions.Items_1_19_4" },
        { "1.20", "MineSharp.Data.Items.Versions.Items_1_20" },
        { "1.20.1", "MineSharp.Data.Items.Versions.Items_1_20" },
        { "1.20.2", "MineSharp.Data.Items.Versions.Items_1_20_2" },
    };
    public static Dictionary<string, string> Protocol { get; } = new()
    {
        { "1.18", "MineSharp.Data.Protocol.Versions.Protocol_1_18" },
        { "1.18.1", "MineSharp.Data.Protocol.Versions.Protocol_1_18" },
        { "1.18.2", "MineSharp.Data.Protocol.Versions.Protocol_1_18_2" },
        { "1.19", "MineSharp.Data.Protocol.Versions.Protocol_1_19" },
        { "1.19.2", "MineSharp.Data.Protocol.Versions.Protocol_1_19_2" },
        { "1.19.3", "MineSharp.Data.Protocol.Versions.Protocol_1_19_3" },
        { "1.19.4", "MineSharp.Data.Protocol.Versions.Protocol_1_19_4" },
        { "1.20", "MineSharp.Data.Protocol.Versions.Protocol_1_20" },
        { "1.20.1", "MineSharp.Data.Protocol.Versions.Protocol_1_20" },
        { "1.20.2", "MineSharp.Data.Protocol.Versions.Protocol_1_20_2" },
    };
    public static Dictionary<string, string> Materials { get; } = new()
    {
        { "1.18", "MineSharp.Data.Materials.Versions.Materials_1_18" },
        { "1.18.1", "MineSharp.Data.Materials.Versions.Materials_1_18" },
        { "1.18.2", "MineSharp.Data.Materials.Versions.Materials_1_18" },
        { "1.19", "MineSharp.Data.Materials.Versions.Materials_1_19" },
        { "1.19.2", "MineSharp.Data.Materials.Versions.Materials_1_19_2" },
        { "1.19.3", "MineSharp.Data.Materials.Versions.Materials_1_19_3" },
        { "1.19.4", "MineSharp.Data.Materials.Versions.Materials_1_19_4" },
        { "1.20", "MineSharp.Data.Materials.Versions.Materials_1_20" },
        { "1.20.1", "MineSharp.Data.Materials.Versions.Materials_1_20" },
        { "1.20.2", "MineSharp.Data.Materials.Versions.Materials_1_20_2" },
    };
    public static Dictionary<string, MinecraftVersion> Versions { get; } = new()
    {
        { "1.18", new MinecraftVersion("1.18", 757) },
        { "1.18.1", new MinecraftVersion("1.18.1", 757) },
        { "1.18.2", new MinecraftVersion("1.18.2", 758) },
        { "1.19", new MinecraftVersion("1.19", 759) },
        { "1.19.2", new MinecraftVersion("1.19.2", 760) },
        { "1.19.3", new MinecraftVersion("1.19.3", 761) },
        { "1.19.4", new MinecraftVersion("1.19.4", 762) },
        { "1.20", new MinecraftVersion("1.20", 763) },
        { "1.20.1", new MinecraftVersion("1.20.1", 763) },
        { "1.20.2", new MinecraftVersion("1.20.2", 764) },
    };
}
