///////////////////////////////////////////////////////////////////////////////////////////
//    This File is generated by MineSharp.SourceGenerator and should not be modified.    //
///////////////////////////////////////////////////////////////////////////////////////////

#pragma warning disable CS1591

namespace MineSharp.Core.Common.Effects;

public enum EffectType
{
    Speed = 0,
    Slowness = 1,
    Haste = 2,
    MiningFatigue = 3,
    Strength = 4,
    InstantHealth = 5,
    InstantDamage = 6,
    JumpBoost = 7,
    Nausea = 8,
    Regeneration = 9,
    Resistance = 10,
    FireResistance = 11,
    WaterBreathing = 12,
    Invisibility = 13,
    Blindness = 14,
    NightVision = 15,
    Hunger = 16,
    Weakness = 17,
    Poison = 18,
    Wither = 19,
    HealthBoost = 20,
    Absorption = 21,
    Saturation = 22,
    Glowing = 23,
    Levitation = 24,
    Luck = 25,
    BadLuck = 26,
    SlowFalling = 27,
    ConduitPower = 28,
    DolphinsGrace = 29,
    BadOmen = 30,
    HeroOfTheVillage = 31,
    Darkness = 32,
    Unluck = 33,
    TrialOmen = 34,
    RaidOmen = 35,
    WindCharged = 36,
    Weaving = 37,
    Oozing = 38,
    Infested = 39,
}

#pragma warning restore CS1591
