using System.Text.RegularExpressions;

namespace MineSharp.PacketSourceGenerator.Utils;

public static class GeneratorHelper
{
	public const string SourceCodeNewLine = """


		""";

	public const string DefaultIndent = "\t";

	public const string AutoGeneratedSourceFileHeader = """
		// ################################################################################
		// #   _    _         _           ____                           _           _ _  #
		// #  | |  / \  _   _| |_ ___    / ___| ___ _ __   ___ _ __ __ _| |_ ___  __| | | #
		// #  | | / _ \| | | | __/ _ \  | |  _ / _ \ '_ \ / _ \ '__/ _` | __/ _ \/ _` | | #
		// #  |_|/ ___ \ |_| | || (_) | | |_| |  __/ | | |  __/ | | (_| | ||  __/ (_| |_| #
		// #  (_)_/   \_\__,_|\__\___/   \____|\___|_| |_|\___|_|  \__,_|\__\___|\__,_(_) #
		// #                                                                              #
		// ################################################################################
		// This file is auto generated.
		// !!DO NOT EDIT THIS FILE!!
		""";

	public static string IndentLines(this string str, int indentCount = 1, string indentString = DefaultIndent, bool ignoreEmptyLines = true, bool ignoreFirstLine = false, Regex? newLineRegex = null, Regex? emptyLineContentRegex = null)
	{
		return str.AddBeforeEachLine(indentString.Repeat(indentCount), ignoreEmptyLines, ignoreFirstLine, newLineRegex, emptyLineContentRegex);
	}

}
