using MineSharp.Data;

namespace MineSharp.Commands.Parser;

internal static class ParserRegistry
{
    private static IDictionary<int, string> Mapping_119 = new Dictionary<int, string>()
    {
        { 0, "brigadier:bool" },
        { 1, "brigadier:float" },
        { 2, "brigadier:double" },
        { 3, "brigadier:integer" },
        { 4, "brigadier:long" },
        { 5, "brigadier:string" },
        { 6, "minecraft:entity" },
        { 7, "minecraft:game_profile" },
        { 8, "minecraft:block_pos" },
        { 9, "minecraft:column_pos" },
        { 10, "minecraft:vec3" },
        { 11, "minecraft:vec2" },
        { 12, "minecraft:block_state" },
        { 13, "minecraft:block_predicate" },
        { 14, "minecraft:item_stack" },
        { 15, "minecraft:item_predicate" },
        { 16, "minecraft:color" },
        { 17, "minecraft:component" },
        { 18, "minecraft:message" },
        { 19, "minecraft:nbt" },
        { 20, "minecraft:nbt_tag" },
        { 21, "minecraft:nbt_path" },
        { 22, "minecraft:objective" },
        { 23, "minecraft:objective_criteria" },
        { 24, "minecraft:operation" },
        { 25, "minecraft:particle" },
        { 26, "minecraft:angle" },
        { 27, "minecraft:rotation" },
        { 28, "minecraft:scoreboard_slot" },
        { 29, "minecraft:score_holder" },
        { 30, "minecraft:swizzle" },
        { 31, "minecraft:team" },
        { 32, "minecraft:item_slot" },
        { 33, "minecraft:resource_location" },
        { 34, "minecraft:mob_effect" },
        { 35, "minecraft:function" },
        { 36, "minecraft:entity_anchor" },
        { 37, "minecraft:int_range" },
        { 38, "minecraft:float_range" },
        { 39, "minecraft:item_enchantment" },
        { 40, "minecraft:entity_summon" },
        { 41, "minecraft:dimension" },
        { 42, "minecraft:time" },
        { 43, "minecraft:resource_or_tag" },
        { 44, "minecraft:resource" },
        { 45, "minecraft:template_mirror" },
        { 46, "minecraft:template_rotation" },
        { 47, "minecraft:uuid" }
    };

    private static IDictionary<int, string> Mapping_1193 = new Dictionary<int, string>()
    {
        { 0, "brigadier:bool" },
        { 1, "brigadier:float" },
        { 2, "brigadier:double" },
        { 3, "brigadier:integer" },
        { 4, "brigadier:long" },
        { 5, "brigadier:string" },
        { 6, "minecraft:entity" },
        { 7, "minecraft:game_profile" },
        { 8, "minecraft:block_pos" },
        { 9, "minecraft:column_pos" },
        { 10, "minecraft:vec3" },
        { 11, "minecraft:vec2" },
        { 12, "minecraft:block_state" },
        { 13, "minecraft:block_predicate" },
        { 14, "minecraft:item_stack" },
        { 15, "minecraft:item_predicate" },
        { 16, "minecraft:color" },
        { 17, "minecraft:component" },
        { 18, "minecraft:message" },
        { 19, "minecraft:nbt" },
        { 20, "minecraft:nbt_tag" },
        { 21, "minecraft:nbt_path" },
        { 22, "minecraft:objective" },
        { 23, "minecraft:objective_criteria" },
        { 24, "minecraft:operation" },
        { 25, "minecraft:particle" },
        { 26, "minecraft:angle" },
        { 27, "minecraft:rotation" },
        { 28, "minecraft:scoreboard_slot" },
        { 29, "minecraft:score_holder" },
        { 30, "minecraft:swizzle" },
        { 31, "minecraft:team" },
        { 32, "minecraft:item_slot" },
        { 33, "minecraft:resource_location" },
        { 34, "minecraft:function" },
        { 35, "minecraft:entity_anchor" },
        { 36, "minecraft:int_range" },
        { 37, "minecraft:float_range" },
        { 38, "minecraft:dimension" },
        { 39, "minecraft:gamemode" },
        { 40, "minecraft:time" },
        { 41, "minecraft:resource_or_tag" },
        { 42, "minecraft:resource_or_tag_key" },
        { 43, "minecraft:resource" },
        { 44, "minecraft:resource_key" },
        { 45, "minecraft:template_mirror" },
        { 46, "minecraft:template_rotation" },
        { 47, "minecraft:uuid" },
    };

    private static IDictionary<int, string> Mapping_1194 = new Dictionary<int, string>()
    {
        { 0, "brigadier:bool" },
        { 1, "brigadier:float" },
        { 2, "brigadier:double" },
        { 3, "brigadier:integer" },
        { 4, "brigadier:long" },
        { 5, "brigadier:string" },
        { 6, "minecraft:entity" },
        { 7, "minecraft:game_profile" },
        { 8, "minecraft:block_pos" },
        { 9, "minecraft:column_pos" },
        { 10, "minecraft:vec3" },
        { 11, "minecraft:vec2" },
        { 12, "minecraft:block_state" },
        { 13, "minecraft:block_predicate" },
        { 14, "minecraft:item_stack" },
        { 15, "minecraft:item_predicate" },
        { 16, "minecraft:color" },
        { 17, "minecraft:component" },
        { 18, "minecraft:message" },
        { 19, "minecraft:nbt" },
        { 20, "minecraft:nbt_tag" },
        { 21, "minecraft:nbt_path" },
        { 22, "minecraft:objective" },
        { 23, "minecraft:objective_criteria" },
        { 24, "minecraft:operation" },
        { 25, "minecraft:particle" },
        { 26, "minecraft:angle" },
        { 27, "minecraft:rotation" },
        { 28, "minecraft:scoreboard_slot" },
        { 29, "minecraft:score_holder" },
        { 30, "minecraft:swizzle" },
        { 31, "minecraft:team" },
        { 32, "minecraft:item_slot" },
        { 33, "minecraft:resource_location" },
        { 34, "minecraft:function" },
        { 35, "minecraft:entity_anchor" },
        { 36, "minecraft:int_range" },
        { 37, "minecraft:float_range" },
        { 38, "minecraft:dimension" },
        { 39, "minecraft:gamemode" },
        { 40, "minecraft:time" },
        { 41, "minecraft:resource_or_tag" },
        { 42, "minecraft:resource_or_tag_key" },
        { 43, "minecraft:resource" },
        { 44, "minecraft:resource_key" },
        { 45, "minecraft:template_mirror" },
        { 46, "minecraft:template_rotation" },
        { 47, "minecraft:heightmap" },
        { 48, "minecraft:uuid" },
    };

    private static IDictionary<int, string> Mapping_1203 = new Dictionary<int, string>()
    {
        { 0, "brigadier:bool" },
        { 1, "brigadier:float" },
        { 2, "brigadier:double" },
        { 3, "brigadier:integer" },
        { 4, "brigadier:long" },
        { 5, "brigadier:string" },
        { 6, "minecraft:entity" },
        { 7, "minecraft:game_profile" },
        { 8, "minecraft:block_pos" },
        { 9, "minecraft:column_pos" },
        { 10, "minecraft:vec3" },
        { 11, "minecraft:vec2" },
        { 12, "minecraft:block_state" },
        { 13, "minecraft:block_predicate" },
        { 14, "minecraft:item_stack" },
        { 15, "minecraft:item_predicate" },
        { 16, "minecraft:color" },
        { 17, "minecraft:component" },
        { 18, "minecraft:style" },
        { 19, "minecraft:message" },
        { 20, "minecraft:nbt" },
        { 21, "minecraft:nbt_tag" },
        { 22, "minecraft:nbt_path" },
        { 23, "minecraft:objective" },
        { 24, "minecraft:objective_criteria" },
        { 25, "minecraft:operation" },
        { 26, "minecraft:particle" },
        { 27, "minecraft:angle" },
        { 28, "minecraft:rotation" },
        { 29, "minecraft:scoreboard_slot" },
        { 30, "minecraft:score_holder" },
        { 31, "minecraft:swizzle" },
        { 32, "minecraft:team" },
        { 33, "minecraft:item_slot" },
        { 34, "minecraft:resource_location" },
        { 35, "minecraft:function" },
        { 36, "minecraft:entity_anchor" },
        { 37, "minecraft:int_range" },
        { 38, "minecraft:float_range" },
        { 39, "minecraft:dimension" },
        { 40, "minecraft:gamemode" },
        { 41, "minecraft:time" },
        { 42, "minecraft:resource_or_tag" },
        { 43, "minecraft:resource_or_tag_key" },
        { 44, "minecraft:resource" },
        { 45, "minecraft:resource_key" },
        { 46, "minecraft:template_mirror" },
        { 47, "minecraft:template_rotation" },
        { 48, "minecraft:heightmap" },
        { 49, "minecraft:uuid" },
    };

    public static string GetParserNameById(int parserId, MinecraftData data)
    {
        var mapping = data.Version.Protocol switch
        {
            ProtocolVersion.V_1_19      => Mapping_119,
            ProtocolVersion.V_1_19_2    => Mapping_119,
            ProtocolVersion.V_1_19_3    => Mapping_1193,
            >= ProtocolVersion.V_1_19_4 and < ProtocolVersion.V_1_20_3 => Mapping_1194,
            >= ProtocolVersion.V_1_20_3 => Mapping_1203,
            _ => throw new NotSupportedException()
        };

        return mapping[parserId];
    }

    public static IParser GetParserByName(string name)
    {
        return name switch
        {
            "brigadier:bool"                => new EmptyParser(),
            "brigadier:float"               => new FloatParser(),
            "brigadier:double"              => new DoubleParser(),
            "brigadier:integer"             => new IntegerParser(),
            "brigadier:long"                => new LongParser(),
            "brigadier:string"              => new StringParser(),
            "minecraft:entity"              => new EntityParser(),
            "minecraft:game_profile"        => new EmptyParser(),
            "minecraft:block_pos"           => new BlockPositionParser(),
            "minecraft:column_pos"          => new ColumnPosParser(),
            "minecraft:vec3"                => new Vec3Parser(),
            "minecraft:vec2"                => new Vec2Parser(),
            "minecraft:block_state"         => new EmptyParser(),
            "minecraft:block_predicate"     => new EmptyParser(),
            "minecraft:item_stack"          => new EmptyParser(),
            "minecraft:item_predicate"      => new EmptyParser(),
            "minecraft:color"               => new EmptyParser(),
            "minecraft:component"           => new EmptyParser(),
            "minecraft:message"             => new MessageParser(),
            "minecraft:nbt"                 => new EmptyParser(),
            "minecraft:nbt_tag"             => new EmptyParser(),
            "minecraft:nbt_path"            => new EmptyParser(),
            "minecraft:objective"           => new EmptyParser(),
            "minecraft:objective_criteria"  => new EmptyParser(),
            "minecraft:operation"           => new EmptyParser(),
            "minecraft:particle"            => new EmptyParser(),
            "minecraft:angle"               => new EmptyParser(),
            "minecraft:rotation"            => new RotationParser(),
            "minecraft:scoreboard_slot"     => new EmptyParser(),
            "minecraft:score_holder"        => new ScoreHolderParser(),
            "minecraft:swizzle"             => new EmptyParser(),
            "minecraft:team"                => new EmptyParser(),
            "minecraft:item_slot"           => new EmptyParser(),
            "minecraft:resource_location"   => new EmptyParser(),
            "minecraft:mob_effect"          => new EmptyParser(),
            "minecraft:function"            => new EmptyParser(),
            "minecraft:entity_anchor"       => new EmptyParser(),
            "minecraft:int_range"           => new EmptyParser(),
            "minecraft:float_range"         => new EmptyParser(),
            "minecraft:item_enchantment"    => new EmptyParser(),
            "minecraft:entity_summon"       => new EmptyParser(),
            "minecraft:dimension"           => new EmptyParser(),
            "minecraft:time"                => new TimeParser(),
            "minecraft:resource_or_tag"     => new ResourceOrTagParser(),
            "minecraft:resource"            => new ResourceParser(),
            "minecraft:template_mirror"     => new EmptyParser(),
            "minecraft:template_rotation"   => new EmptyParser(),
            "minecraft:uuid"                => new EmptyParser(),
            "minecraft:gamemode"            => new EmptyParser(),
            "minecraft:resource_or_tag_key" => new ResourceOrTagParser(),
            "minecraft:resource_key"        => new ResourceParser(),
            "minecraft:heightmap"           => new EmptyParser(),
            "minecraft:range"               => new RangeParser(), // only in 1.18
            "minecraft:nbt_compound_tag"    => new EmptyParser(),
            "minecraft:style"               => new EmptyParser(), // since 1.20.3
            _ => throw new ArgumentException($"Unknown parser: {name}")
        };
    }
}
