using MineSharp.Core;
using MineSharp.Core.Common;
using MineSharp.Data;

namespace MineSharp.Commands.Parser;

internal static class ParserRegistry
{
    private static readonly Dictionary<int, Identifier> Mapping119 = new()
    {
        { 0, Identifier.Parse("brigadier:bool") },
        { 1, Identifier.Parse("brigadier:float") },
        { 2, Identifier.Parse("brigadier:double") },
        { 3, Identifier.Parse("brigadier:integer") },
        { 4, Identifier.Parse("brigadier:long") },
        { 5, Identifier.Parse("brigadier:string") },
        { 6, Identifier.Parse("minecraft:entity") },
        { 7, Identifier.Parse("minecraft:game_profile") },
        { 8, Identifier.Parse("minecraft:block_pos") },
        { 9, Identifier.Parse("minecraft:column_pos") },
        { 10, Identifier.Parse("minecraft:vec3") },
        { 11, Identifier.Parse("minecraft:vec2") },
        { 12, Identifier.Parse("minecraft:block_state") },
        { 13, Identifier.Parse("minecraft:block_predicate") },
        { 14, Identifier.Parse("minecraft:item_stack") },
        { 15, Identifier.Parse("minecraft:item_predicate") },
        { 16, Identifier.Parse("minecraft:color") },
        { 17, Identifier.Parse("minecraft:component") },
        { 18, Identifier.Parse("minecraft:message") },
        { 19, Identifier.Parse("minecraft:nbt") },
        { 20, Identifier.Parse("minecraft:nbt_tag") },
        { 21, Identifier.Parse("minecraft:nbt_path") },
        { 22, Identifier.Parse("minecraft:objective") },
        { 23, Identifier.Parse("minecraft:objective_criteria") },
        { 24, Identifier.Parse("minecraft:operation") },
        { 25, Identifier.Parse("minecraft:particle") },
        { 26, Identifier.Parse("minecraft:angle") },
        { 27, Identifier.Parse("minecraft:rotation") },
        { 28, Identifier.Parse("minecraft:scoreboard_slot") },
        { 29, Identifier.Parse("minecraft:score_holder") },
        { 30, Identifier.Parse("minecraft:swizzle") },
        { 31, Identifier.Parse("minecraft:team") },
        { 32, Identifier.Parse("minecraft:item_slot") },
        { 33, Identifier.Parse("minecraft:resource_location") },
        { 34, Identifier.Parse("minecraft:mob_effect") },
        { 35, Identifier.Parse("minecraft:function") },
        { 36, Identifier.Parse("minecraft:entity_anchor") },
        { 37, Identifier.Parse("minecraft:int_range") },
        { 38, Identifier.Parse("minecraft:float_range") },
        { 39, Identifier.Parse("minecraft:item_enchantment") },
        { 40, Identifier.Parse("minecraft:entity_summon") },
        { 41, Identifier.Parse("minecraft:dimension") },
        { 42, Identifier.Parse("minecraft:time") },
        { 43, Identifier.Parse("minecraft:resource_or_tag") },
        { 44, Identifier.Parse("minecraft:resource") },
        { 45, Identifier.Parse("minecraft:template_mirror") },
        { 46, Identifier.Parse("minecraft:template_rotation") },
        { 47, Identifier.Parse("minecraft:uuid") }
    };

    private static readonly Dictionary<int, Identifier> Mapping1193 = new()
    {
        { 0, Identifier.Parse("brigadier:bool") },
        { 1, Identifier.Parse("brigadier:float") },
        { 2, Identifier.Parse("brigadier:double") },
        { 3, Identifier.Parse("brigadier:integer") },
        { 4, Identifier.Parse("brigadier:long") },
        { 5, Identifier.Parse("brigadier:string") },
        { 6, Identifier.Parse("minecraft:entity") },
        { 7, Identifier.Parse("minecraft:game_profile") },
        { 8, Identifier.Parse("minecraft:block_pos") },
        { 9, Identifier.Parse("minecraft:column_pos") },
        { 10, Identifier.Parse("minecraft:vec3") },
        { 11, Identifier.Parse("minecraft:vec2") },
        { 12, Identifier.Parse("minecraft:block_state") },
        { 13, Identifier.Parse("minecraft:block_predicate") },
        { 14, Identifier.Parse("minecraft:item_stack") },
        { 15, Identifier.Parse("minecraft:item_predicate") },
        { 16, Identifier.Parse("minecraft:color") },
        { 17, Identifier.Parse("minecraft:component") },
        { 18, Identifier.Parse("minecraft:message") },
        { 19, Identifier.Parse("minecraft:nbt") },
        { 20, Identifier.Parse("minecraft:nbt_tag") },
        { 21, Identifier.Parse("minecraft:nbt_path") },
        { 22, Identifier.Parse("minecraft:objective") },
        { 23, Identifier.Parse("minecraft:objective_criteria") },
        { 24, Identifier.Parse("minecraft:operation") },
        { 25, Identifier.Parse("minecraft:particle") },
        { 26, Identifier.Parse("minecraft:angle") },
        { 27, Identifier.Parse("minecraft:rotation") },
        { 28, Identifier.Parse("minecraft:scoreboard_slot") },
        { 29, Identifier.Parse("minecraft:score_holder") },
        { 30, Identifier.Parse("minecraft:swizzle") },
        { 31, Identifier.Parse("minecraft:team") },
        { 32, Identifier.Parse("minecraft:item_slot") },
        { 33, Identifier.Parse("minecraft:resource_location") },
        { 34, Identifier.Parse("minecraft:function") },
        { 35, Identifier.Parse("minecraft:entity_anchor") },
        { 36, Identifier.Parse("minecraft:int_range") },
        { 37, Identifier.Parse("minecraft:float_range") },
        { 38, Identifier.Parse("minecraft:dimension") },
        { 39, Identifier.Parse("minecraft:gamemode") },
        { 40, Identifier.Parse("minecraft:time") },
        { 41, Identifier.Parse("minecraft:resource_or_tag") },
        { 42, Identifier.Parse("minecraft:resource_or_tag_key") },
        { 43, Identifier.Parse("minecraft:resource") },
        { 44, Identifier.Parse("minecraft:resource_key") },
        { 45, Identifier.Parse("minecraft:template_mirror") },
        { 46, Identifier.Parse("minecraft:template_rotation") },
        { 47, Identifier.Parse("minecraft:uuid") }
    };

    private static readonly Dictionary<int, Identifier> Mapping1194 = new()
    {
        { 0, Identifier.Parse("brigadier:bool") },
        { 1, Identifier.Parse("brigadier:float") },
        { 2, Identifier.Parse("brigadier:double") },
        { 3, Identifier.Parse("brigadier:integer") },
        { 4, Identifier.Parse("brigadier:long") },
        { 5, Identifier.Parse("brigadier:string") },
        { 6, Identifier.Parse("minecraft:entity") },
        { 7, Identifier.Parse("minecraft:game_profile") },
        { 8, Identifier.Parse("minecraft:block_pos") },
        { 9, Identifier.Parse("minecraft:column_pos") },
        { 10, Identifier.Parse("minecraft:vec3") },
        { 11, Identifier.Parse("minecraft:vec2") },
        { 12, Identifier.Parse("minecraft:block_state") },
        { 13, Identifier.Parse("minecraft:block_predicate") },
        { 14, Identifier.Parse("minecraft:item_stack") },
        { 15, Identifier.Parse("minecraft:item_predicate") },
        { 16, Identifier.Parse("minecraft:color") },
        { 17, Identifier.Parse("minecraft:component") },
        { 18, Identifier.Parse("minecraft:message") },
        { 19, Identifier.Parse("minecraft:nbt") },
        { 20, Identifier.Parse("minecraft:nbt_tag") },
        { 21, Identifier.Parse("minecraft:nbt_path") },
        { 22, Identifier.Parse("minecraft:objective") },
        { 23, Identifier.Parse("minecraft:objective_criteria") },
        { 24, Identifier.Parse("minecraft:operation") },
        { 25, Identifier.Parse("minecraft:particle") },
        { 26, Identifier.Parse("minecraft:angle") },
        { 27, Identifier.Parse("minecraft:rotation") },
        { 28, Identifier.Parse("minecraft:scoreboard_slot") },
        { 29, Identifier.Parse("minecraft:score_holder") },
        { 30, Identifier.Parse("minecraft:swizzle") },
        { 31, Identifier.Parse("minecraft:team") },
        { 32, Identifier.Parse("minecraft:item_slot") },
        { 33, Identifier.Parse("minecraft:resource_location") },
        { 34, Identifier.Parse("minecraft:function") },
        { 35, Identifier.Parse("minecraft:entity_anchor") },
        { 36, Identifier.Parse("minecraft:int_range") },
        { 37, Identifier.Parse("minecraft:float_range") },
        { 38, Identifier.Parse("minecraft:dimension") },
        { 39, Identifier.Parse("minecraft:gamemode") },
        { 40, Identifier.Parse("minecraft:time") },
        { 41, Identifier.Parse("minecraft:resource_or_tag") },
        { 42, Identifier.Parse("minecraft:resource_or_tag_key") },
        { 43, Identifier.Parse("minecraft:resource") },
        { 44, Identifier.Parse("minecraft:resource_key") },
        { 45, Identifier.Parse("minecraft:template_mirror") },
        { 46, Identifier.Parse("minecraft:template_rotation") },
        { 47, Identifier.Parse("minecraft:heightmap") },
        { 48, Identifier.Parse("minecraft:uuid") }
    };

    private static readonly Dictionary<int, Identifier> Mapping1203 = new()
    {
        { 0, Identifier.Parse("brigadier:bool") },
        { 1, Identifier.Parse("brigadier:float") },
        { 2, Identifier.Parse("brigadier:double") },
        { 3, Identifier.Parse("brigadier:integer") },
        { 4, Identifier.Parse("brigadier:long") },
        { 5, Identifier.Parse("brigadier:string") },
        { 6, Identifier.Parse("minecraft:entity") },
        { 7, Identifier.Parse("minecraft:game_profile") },
        { 8, Identifier.Parse("minecraft:block_pos") },
        { 9, Identifier.Parse("minecraft:column_pos") },
        { 10, Identifier.Parse("minecraft:vec3") },
        { 11, Identifier.Parse("minecraft:vec2") },
        { 12, Identifier.Parse("minecraft:block_state") },
        { 13, Identifier.Parse("minecraft:block_predicate") },
        { 14, Identifier.Parse("minecraft:item_stack") },
        { 15, Identifier.Parse("minecraft:item_predicate") },
        { 16, Identifier.Parse("minecraft:color") },
        { 17, Identifier.Parse("minecraft:component") },
        { 18, Identifier.Parse("minecraft:style") },
        { 19, Identifier.Parse("minecraft:message") },
        { 20, Identifier.Parse("minecraft:nbt") },
        { 21, Identifier.Parse("minecraft:nbt_tag") },
        { 22, Identifier.Parse("minecraft:nbt_path") },
        { 23, Identifier.Parse("minecraft:objective") },
        { 24, Identifier.Parse("minecraft:objective_criteria") },
        { 25, Identifier.Parse("minecraft:operation") },
        { 26, Identifier.Parse("minecraft:particle") },
        { 27, Identifier.Parse("minecraft:angle") },
        { 28, Identifier.Parse("minecraft:rotation") },
        { 29, Identifier.Parse("minecraft:scoreboard_slot") },
        { 30, Identifier.Parse("minecraft:score_holder") },
        { 31, Identifier.Parse("minecraft:swizzle") },
        { 32, Identifier.Parse("minecraft:team") },
        { 33, Identifier.Parse("minecraft:item_slot") },
        { 34, Identifier.Parse("minecraft:resource_location") },
        { 35, Identifier.Parse("minecraft:function") },
        { 36, Identifier.Parse("minecraft:entity_anchor") },
        { 37, Identifier.Parse("minecraft:int_range") },
        { 38, Identifier.Parse("minecraft:float_range") },
        { 39, Identifier.Parse("minecraft:dimension") },
        { 40, Identifier.Parse("minecraft:gamemode") },
        { 41, Identifier.Parse("minecraft:time") },
        { 42, Identifier.Parse("minecraft:resource_or_tag") },
        { 43, Identifier.Parse("minecraft:resource_or_tag_key") },
        { 44, Identifier.Parse("minecraft:resource") },
        { 45, Identifier.Parse("minecraft:resource_key") },
        { 46, Identifier.Parse("minecraft:template_mirror") },
        { 47, Identifier.Parse("minecraft:template_rotation") },
        { 48, Identifier.Parse("minecraft:heightmap") },
        { 49, Identifier.Parse("minecraft:uuid") }
    };

    public static Identifier GetParserNameById(int parserId, MinecraftData data)
    {
        var mapping = data.Version.Protocol switch
        {
            ProtocolVersion.V_1_19 => Mapping119,
            ProtocolVersion.V_1_19_2 => Mapping119,
            ProtocolVersion.V_1_19_3 => Mapping1193,
            >= ProtocolVersion.V_1_19_4 and < ProtocolVersion.V_1_20_3 => Mapping1194,
            >= ProtocolVersion.V_1_20_3 => Mapping1203,
            _ => throw new NotSupportedException()
        };

        return mapping[parserId];
    }

    public static IParser GetParserByName(Identifier name)
    {
        return name.ToString() switch
        {
            "brigadier:bool" => new EmptyParser(),
            "brigadier:float" => new FloatParser(),
            "brigadier:double" => new DoubleParser(),
            "brigadier:integer" => new IntegerParser(),
            "brigadier:long" => new LongParser(),
            "brigadier:string" => new StringParser(),
            "minecraft:entity" => new EntityParser(),
            "minecraft:game_profile" => new EmptyParser(),
            "minecraft:block_pos" => new BlockPositionParser(),
            "minecraft:column_pos" => new ColumnPosParser(),
            "minecraft:vec3" => new Vec3Parser(),
            "minecraft:vec2" => new Vec2Parser(),
            "minecraft:block_state" => new EmptyParser(),
            "minecraft:block_predicate" => new EmptyParser(),
            "minecraft:item_stack" => new EmptyParser(),
            "minecraft:item_predicate" => new EmptyParser(),
            "minecraft:color" => new EmptyParser(),
            "minecraft:component" => new EmptyParser(),
            "minecraft:message" => new MessageParser(),
            "minecraft:nbt" => new EmptyParser(),
            "minecraft:nbt_tag" => new EmptyParser(),
            "minecraft:nbt_path" => new EmptyParser(),
            "minecraft:objective" => new EmptyParser(),
            "minecraft:objective_criteria" => new EmptyParser(),
            "minecraft:operation" => new EmptyParser(),
            "minecraft:particle" => new EmptyParser(),
            "minecraft:angle" => new EmptyParser(),
            "minecraft:rotation" => new RotationParser(),
            "minecraft:scoreboard_slot" => new EmptyParser(),
            "minecraft:score_holder" => new ScoreHolderParser(),
            "minecraft:swizzle" => new EmptyParser(),
            "minecraft:team" => new EmptyParser(),
            "minecraft:item_slot" => new EmptyParser(),
            "minecraft:resource_location" => new EmptyParser(),
            "minecraft:mob_effect" => new EmptyParser(),
            "minecraft:function" => new EmptyParser(),
            "minecraft:entity_anchor" => new EmptyParser(),
            "minecraft:int_range" => new EmptyParser(),
            "minecraft:float_range" => new EmptyParser(),
            "minecraft:item_enchantment" => new EmptyParser(),
            "minecraft:entity_summon" => new EmptyParser(),
            "minecraft:dimension" => new EmptyParser(),
            "minecraft:time" => new TimeParser(),
            "minecraft:resource_or_tag" => new ResourceOrTagParser(),
            "minecraft:resource" => new ResourceParser(),
            "minecraft:template_mirror" => new EmptyParser(),
            "minecraft:template_rotation" => new EmptyParser(),
            "minecraft:uuid" => new EmptyParser(),
            "minecraft:gamemode" => new EmptyParser(),
            "minecraft:resource_or_tag_key" => new ResourceOrTagParser(),
            "minecraft:resource_key" => new ResourceParser(),
            "minecraft:heightmap" => new EmptyParser(),
            "minecraft:range" => new RangeParser(), // only in 1.18
            "minecraft:nbt_compound_tag" => new EmptyParser(),
            "minecraft:style" => new EmptyParser(), // since 1.20.3
            _ => throw new ArgumentException($"Unknown parser: {name}")
        };
    }
}
